# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call(`_anpai_rcpp_hello_world`)
}

read_ics_rcpp <- function(path) {
    .Call(`_anpai_read_ics_rcpp`, path)
}

